# List of rules:
# https://realm.github.io/SwiftLint/rule-directory.html

swiftlint_version: 0.39.2
indentation: 4


identifier_name:
    min_length:
        warning: 0
        error: 0

type_body_length:
    warning: 500
    error: 1000
